[pytest]
addopts = -v --tb=short
testpaths = tests
markers =
    smoke: mark test as smoke
    regression: mark test as regression
    login: mark test for login functionality
    post_creation: mark test for post creation functionality